---
title: "Córpora - critérios"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

# critérios
ini <- 2016
fim <- 2017
partido <- "PT"

if(!require(stringr)) { install.packages('stringr') }

source("..\\02_2017MaiJun\\05_EncodeDecode.R")
source("..\\02_2017MaiJun\\07_CorporaRetiraQuadrosFiguras.R")

print(sprintf("Partido: %s (%d - %d)", partido, ini, fim))

```

### Lê arquivo de discursos

```{r}
# lê arquivo com todos os discursos
pastaorig <- "..\\DadosRDS\\"
discursos <- readRDS(paste0(pastaorig, "discurso_2000_2017.rds"))
names(discursos)[1] <- "seq"
```

### Verifica frequência de [sessões](http://www2.camara.leg.br/comunicacao/assessoria-de-imprensa/sessoes-do-plenario) por tipo e restringe às sessões relevantes

```{r}
# frequência por tipo de sessao
tipo_sessao <- table(discursos$tipoSessao)
tipo_sessao
# filtra sessões relevantes
tipo_sessao <- as.character(levels(as.factor(discursos$tipoSessao)))
tipo_sessao <- tipo_sessao[c(3:8, 12, 14:15, 18:19)]
discursos <- discursos[discursos$tipoSessao %in% tipo_sessao, ]
tipo_sessao
```

### Lê arquivo de discursos e aplica critérios iniciais de filtragem

```{r}
pastadest <- "..\\CorporaRDS\\"
arquivo <- paste0(pastadest, "corpora_", partido, "_", ini, "_", fim, ".rds")

discursos <- discursos[  str_sub(discursos$dataSessao,7,10) >= ini 
                       & str_sub(discursos$dataSessao,7,10) <= fim 
                       & discursos$partidoOrador == partido
                       , 
                      ]

dim(discursos)
```

### Constroi vetor com os discursos

```{r}
pt1 <- proc.time()

ano <- "0000"
n <- nrow(discursos)
vdisc <- vector("character", n)

#oradores <- as.character(levels(as.factor(discursos$nomeOrador)))
#oradores <- retira_acentos(str_to_lower(oradores))

for(i in 1:n){
  
  # a cada mudança de ano, abre o respectivo "discurso_AAAA_dit.rds"
  if(ano != str_sub(discursos$dataSessao[i], 7, 10)){
    ano <- str_sub(discursos$dataSessao[i], 7, 10)
    arq <- paste0(pastaorig, "discurso_", ano,"_dit.rds")
    discurso_it <- readRDS(arq)
  }

  # monta o id com base no ano e no sequencial do discurso
  id <- paste0('00000', discursos$seq[i])
  id <- str_sub(id,str_length(id)-4,str_length(id))
  id <- paste0(ano,id)

  # retira discursos 'sujos' com excesso de caracteres de controle
  if( (ano == 2012) & (discursos$seq[i] %in% 6862:6879) ){
    vdisc[i] <- ""
    next
  }

  if(!is.na(discurso_it$Discurso[i]) & (discurso_it$Discurso[i] != "")){
    discurso <- decode_rtf(discurso_it$Discurso[i])

    # retira figura, tabela ou quadro
    discurso <- retira_fig(discurso, ano)
    
    # retira a apresentação do discurso: "SR, PRESIDENTE ..."
    discurso <- str_sub(discurso,
                        str_locate(discurso, "\\)")[1]+1,
                        str_length(discurso)
                       )
    
    # converte para minúsculo
    # discurso <- str_to_lower(discurso)
    
    # remove plural
    # discurso <- remove_plural(discurso)

    # retira acentos e cedilha
    # discurso <- retira_acentos(discurso)
    
    # retira nome de oradores
    #for(orador in oradores){
    #  try(discurso <- gsub(orador, "", discurso), silent = TRUE)
    #}
    
    # adiciona ao vetor de discursos
    vdisc[i] <- discurso
  }
}
rm(discurso_it)

vdisc <- vdisc[vdisc != ""]

saveRDS(vdisc, arquivo)

length(vdisc)

pt2 <- proc.time()

pt2 - pt1
```

